"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL;
type Status="PENDING"|"APPROVED"|"REJECTED";
type A={id:number;title:string;studentName:string;department?:string;category?:string;description?:string;proofUrl?:string;status:Status;createdAt?:string};
export default function Admin(){const router=useRouter();const [items,setItems]=useState<A[]>([]),[msg,setMsg]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState<"ALL"|Status>("ALL"),[busy,setBusy]=useState<number|null>(null);
 const token=()=>typeof window==="undefined"?"":sessionStorage.getItem("rkgitm_token")||"";
 useEffect(()=>{if(typeof window!=="undefined"&&!sessionStorage.getItem("rkgitm_token"))router.replace("/login")},[router]);
 async function load(){if(!API){setMsg("Preview mode — connect the deployed backend to manage live records.");return}try{const r=await fetch(API+"/api/achievements/admin",{headers:{Authorization:"Bearer "+token()}});if(r.status===401||r.status===403){sessionStorage.removeItem("rkgitm_token");router.replace("/login");return}if(!r.ok)throw new Error();setItems(await r.json());setMsg("")}catch{setMsg("Admin service is currently unavailable.")}}
 useEffect(()=>{void load()},[]);
 async function decide(id:number,value:Status){if(!API)return;setBusy(id);try{const r=await fetch(API+`/api/achievements/${id}/status?value=${value}`,{method:"PATCH",headers:{Authorization:"Bearer "+token()}});if(!r.ok)throw new Error();setItems(v=>v.map(x=>x.id===id?{...x,status:value}:x))}catch{setMsg("Could not update this record. Please retry.")}finally{setBusy(null)}}
 const counts=useMemo(()=>({all:items.length,pending:items.filter(x=>x.status==="PENDING").length,approved:items.filter(x=>x.status==="APPROVED").length,rejected:items.filter(x=>x.status==="REJECTED").length}),[items]);
 const shown=useMemo(()=>items.filter(a=>(filter==="ALL"||a.status===filter)&&(a.title+" "+a.studentName+" "+(a.department||"")+" "+(a.category||"")).toLowerCase().includes(query.toLowerCase())),[items,query,filter]);
 return <main className="adminShell"><aside className="sideNav"><div className="brandMark">RA</div><div><strong>Achievement Hub</strong><small>Admin Panel</small></div><nav><a className="active" href="/admin">All Records</a><a href="/faculty">Verification Queue</a><a href="/achievements">Published Records</a><a href="/submit">Submit Achievement</a><a href="/">Public Website</a></nav><div className="sideFoot">RKGITM • Administration</div></aside>
 <section className="adminMain"><header className="adminTop"><div><p className="eyebrow">ADMIN CONTROL CENTER</p><h1>Achievement Records</h1><p>Review, publish and manage the institutional achievement pipeline from one workspace.</p></div><div className="topActions"><div className="adminBadge">Authorized</div><button className="logoutBtn" onClick={()=>{sessionStorage.removeItem("rkgitm_token");router.replace("/login")}}>Sign out</button></div></header>
 <div className="adminStats"><button onClick={()=>setFilter("ALL")} className={filter==="ALL"?"selected":""}><span>Total</span><strong>{counts.all}</strong></button><button onClick={()=>setFilter("PENDING")} className={filter==="PENDING"?"selected":""}><span>Pending</span><strong>{counts.pending}</strong></button><button onClick={()=>setFilter("APPROVED")} className={filter==="APPROVED"?"selected":""}><span>Approved</span><strong>{counts.approved}</strong></button><button onClick={()=>setFilter("REJECTED")} className={filter==="REJECTED"?"selected":""}><span>Rejected</span><strong>{counts.rejected}</strong></button></div>
 <div className="toolbar"><input aria-label="Search records" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search student, title, department or category…"/><span>{shown.length} record{shown.length===1?"":"s"}</span></div>
 {msg&&<div className="adminNotice">{msg}</div>}<div className="reviewList">{shown.map(a=><article className="reviewCard" key={a.id}><div className="reviewMeta"><span>{a.category||"Achievement"}</span><span>{a.department||"Department not provided"}</span><span className={"statusPill "+a.status.toLowerCase()}>{a.status}</span></div><h2>{a.title}</h2><strong>{a.studentName}</strong><p>{a.description}</p>{a.proofUrl&&<a className="proof" href={a.proofUrl} target="_blank" rel="noreferrer">View supporting evidence ↗</a>}<div className="reviewActions"><button disabled={busy===a.id} onClick={()=>decide(a.id,"APPROVED")}>Approve</button><button disabled={busy===a.id} className="reject" onClick={()=>decide(a.id,"REJECTED")}>Reject</button>{a.status!=="PENDING"&&<button disabled={busy===a.id} className="resetBtn" onClick={()=>decide(a.id,"PENDING")}>Return to review</button>}</div></article>)}</div>
 {shown.length===0&&!msg&&<div className="adminEmpty"><span>✓</span><h2>No records in this view.</h2><p>Change the filter or search term to continue.</p></div>}</section></main>}