"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL;
type User={uid:string;name?:string;department?:string;studyYear?:string;active:boolean;archived?:boolean;createdAt?:string;lastActiveAt?:string;archivedAt?:string};
type Audit={id:number;actorUid:string;action:string;targetType?:string;targetId?:string;details?:string;createdAt:string};
type Overview={registeredStudents:number;liveStudents:number;registeredFaculty:number;liveFaculty:number;pendingFaculty:number;pendingStudents:number;approvedAchievements:number;pendingAchievements:number;projects:number;research:number;events:number;students:User[];faculty:User[];archivedFaculty:User[];recentAudit:Audit[]};
type ConfirmState={kind:"archive"|"reset";user:User}|null;
export default function Admin(){
 const router=useRouter();const [data,setData]=useState<Overview|null>(null),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[tab,setTab]=useState<"students"|"faculty"|"archived">("students"),[q,setQ]=useState(""),[dept,setDept]=useState("ALL"),[status,setStatus]=useState("ALL"),[confirm,setConfirm]=useState<ConfirmState>(null),[tempPassword,setTempPassword]=useState(""),[now,setNow]=useState(Date.now());
 const token=()=>typeof window==="undefined"?"":sessionStorage.getItem("rkgitm_token")||"";
 async function load(){if(!API){setMsg("Backend connection unavailable.");setLoading(false);return}try{const r=await fetch(API+"/api/super-admin/overview",{headers:{Authorization:"Bearer "+token()}});if(r.status===401||r.status===403){router.replace("/login");return}if(!r.ok)throw new Error();setData(await r.json())}catch{setMsg("Could not load control center.")}finally{setLoading(false)}}
 useEffect(()=>{if(sessionStorage.getItem("rkgitm_role")!=="ADMIN"){router.replace("/login");return}void load();const refresh=setInterval(()=>{setNow(Date.now());void load()},15000);const onFocus=()=>void load();window.addEventListener("focus",onFocus);return()=>{clearInterval(refresh);window.removeEventListener("focus",onFocus)}},[]);
 useEffect(()=>{if(!msg)return;const t=setTimeout(()=>setMsg(""),3500);return()=>clearTimeout(t)},[msg]);
 async function toggle(u:User){if(!API)return;const r=await fetch(API+`/api/super-admin/users/${encodeURIComponent(u.uid)}/active?value=${!u.active}`,{method:"PATCH",headers:{Authorization:"Bearer "+token()}});if(r.ok){setMsg(`${u.name||u.uid} ${u.active?"deactivated":"activated"}.`);void load()}}
 async function archive(u:User){if(!API)return;const kind=tab==="students"?"student":"faculty";const r=await fetch(API+`/api/super-admin/${kind}/${encodeURIComponent(u.uid)}`,{method:"DELETE",headers:{Authorization:"Bearer "+token()}});setConfirm(null);if(r.ok){setMsg(`${kind==="student"?"Student":"Faculty"} account removed from active accounts and safely archived.`);void load()}else setMsg(`Could not delete ${kind} account.`)}
 async function restore(u:User){if(!API)return;const r=await fetch(API+`/api/super-admin/faculty/${encodeURIComponent(u.uid)}/restore`,{method:"PATCH",headers:{Authorization:"Bearer "+token()}});if(r.ok){setMsg("Faculty account restored and activated.");void load()}}
 async function resetPassword(u:User){if(!API)return;const r=await fetch(API+`/api/super-admin/users/${encodeURIComponent(u.uid)}/reset-password`,{method:"POST",headers:{Authorization:"Bearer "+token()}});setConfirm(null);if(r.ok){const x=await r.json();setTempPassword(x.temporaryPassword);setMsg(`Temporary password generated for ${u.name||u.uid}.`)}else setMsg("Could not reset password.")}
 const base=tab==="students"?data?.students:tab==="faculty"?data?.faculty:data?.archivedFaculty;
 const departments=useMemo(()=>Array.from(new Set([...(data?.students||[]),...(data?.faculty||[])].map(x=>x.department).filter(Boolean) as string[])).sort(),[data]);
 const users=(base||[]).filter(u=>{const text=(u.name+" "+u.uid+" "+u.department).toLowerCase();return text.includes(q.toLowerCase())&&(dept==="ALL"||u.department===dept)&&(status==="ALL"||status==="ACTIVE"&&u.active||status==="INACTIVE"&&!u.active)});
 const analytics=[["Students",data?.registeredStudents||0,data?.liveStudents||0],["Faculty",data?.registeredFaculty||0,data?.liveFaculty||0],["Achievements",data?.approvedAchievements||0,data?.pendingAchievements||0],["Projects",data?.projects||0,0],["Research",data?.research||0,0]];
 const max=Math.max(1,...analytics.map(x=>Number(x[1])));
 function exportCsv(){const rows=[["UID","Name","Department","Status","Created","Last Active"],...users.map(u=>[u.uid,u.name||"",u.department||"",u.archived?"Archived":u.active?"Active":"Inactive",u.createdAt||"",u.lastActiveAt||""])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`rkgitm-${tab}-report.csv`;a.click();URL.revokeObjectURL(url)}
 function ago(v?:string){if(!v)return"Never";const s=Math.floor((Date.now()-new Date(v).getTime())/1000);if(s<60)return"Just now";if(s<3600)return Math.floor(s/60)+"m ago";if(s<86400)return Math.floor(s/3600)+"h ago";return Math.floor(s/86400)+"d ago"}
 return <main className="saShell"><section className="saMain">
  <header className="saHeader"><div><p>ADMINISTRATION / OVERVIEW</p><h1>Control Center</h1><span>Institutional analytics, approvals, security and account health.</span></div><div className="saHeaderActions"><a href="/">Public site ↗</a><a href="/account/security">Security</a><button onClick={()=>{sessionStorage.clear();router.replace("/login")}}>Sign out</button></div></header>
  {msg&&<div className="saAlert">{msg}</div>}{tempPassword&&<div className="saTempPass"><span>Temporary password</span><strong>{tempPassword}</strong><button onClick={()=>navigator.clipboard.writeText(tempPassword)}>Copy</button><button onClick={()=>setTempPassword("")}>×</button></div>}
  {loading?<div className="saSkeleton"><i/><i/><i/><i/></div>:<>
  <div className="saKpis"><article><span>Students</span><strong>{data?.registeredStudents??0}</strong><small><b>{data?.liveStudents??0}</b> active accounts</small></article><article><span>Faculty</span><strong>{data?.registeredFaculty??0}</strong><small><b>{data?.liveFaculty??0}</b> active accounts</small></article><article className={(data?.pendingFaculty||0)>0?"attention":""}><span>Faculty approvals</span><strong>{data?.pendingFaculty||0}</strong>{(data?.pendingFaculty||0)>0?<a href="/admin/identities">Review faculty requests →</a>:<small>No pending faculty requests</small>}</article><article><span>Verified work</span><strong>{(data?.approvedAchievements||0)+(data?.projects||0)+(data?.research||0)}</strong><small>Achievements + projects + research</small></article></div>
  <section className="saPanel saAnalytics"><div className="saPanelHead"><div><p>LIVE ANALYTICS</p><h2>Institution activity</h2></div><div className="saReportBtns"><button onClick={exportCsv}>Export CSV</button><button onClick={()=>window.print()}>Print / Save PDF</button></div></div><div className="saBars">{analytics.map(([label,value,secondary])=><div key={String(label)}><span>{label}</span><div><i style={{width:`${Math.max(4,Number(value)/max*100)}%`}}/></div><strong>{value}</strong></div>)}</div></section>
  <div className="saGrid"><section className="saPanel saAccounts"><div className="saPanelHead"><div><p>ACCOUNT DIRECTORY</p><h2>Campus accounts</h2></div><div className="saTabs"><button className={tab==="students"?"on":""} onClick={()=>setTab("students")}>Students</button><button className={tab==="faculty"?"on":""} onClick={()=>setTab("faculty")}>Faculty</button><button className={tab==="archived"?"on":""} onClick={()=>setTab("archived")}>Archived</button></div></div>
   <div className="saFilters"><div className="saSearch"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, UID or department"/></div><select value={dept} onChange={e=>setDept(e.target.value)}><option value="ALL">All departments</option>{departments.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All status</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div>
   <div className="saTable"><div className="saTr head"><span>Person</span><span>Department</span><span>Status / activity</span><span>Actions</span></div>{users.map(u=><div className="saTr" key={u.uid}><span><b>{(u.name||u.uid).slice(0,1).toUpperCase()}</b><i><strong>{u.name||"Unnamed user"}</strong><small>{u.uid}{u.studyYear?" • "+u.studyYear:""}</small></i></span><span>{u.department||"—"}</span><span><mark className={u.archived?"off":u.active?"live":"off"}>{u.archived?"Archived":u.active?"● Active":"○ Inactive"}</mark><small className="saAgo">{u.archived?"Archived "+ago(u.archivedAt):"Last active "+ago(u.lastActiveAt)}</small></span><span className="saAccountActions">{u.archived?<button onClick={()=>void restore(u)}>Restore</button>:<><button onClick={()=>void toggle(u)}>{u.active?"Deactivate":"Activate"}</button><button onClick={()=>setConfirm({kind:"reset",user:u})}>Reset password</button>{(tab==="faculty"||tab==="students")&&<button className="saDeleteBtn" onClick={()=>setConfirm({kind:"archive",user:u})}>Delete</button>}</>}</span></div>)}</div>{users.length===0&&<div className="saEmpty">No matching accounts.</div>}</section>
   <aside className="saPanel saQuick"><p>NEEDS ATTENTION</p><h2>Approval queue</h2><a href="/admin/identities"><span>Faculty identity requests</span><strong>{data?.pendingFaculty||0}</strong><small>Review access →</small></a><a href="/faculty"><span>Student + achievement approvals</span><strong>{(data?.pendingStudents||0)+(data?.pendingAchievements||0)}</strong><small>Open faculty workflow →</small></a><a href="/admin/content"><span>Content workspace</span><b>Manage</b><small>Projects, research & events →</small></a></aside></div>
  <section className="saPanel saAudit"><div className="saPanelHead"><div><p>AUDIT TRAIL</p><h2>Recent institutional activity</h2></div></div><div className="auditList">{(data?.recentAudit||[]).map(a=><article key={a.id}><span>{a.action.replaceAll("_"," ")}</span><div><strong>{a.actorUid}</strong><p>{a.details||a.targetId}</p></div><time>{new Date(a.createdAt).toLocaleString()}</time></article>)}{!data?.recentAudit?.length&&<p>No audit events yet.</p>}</div></section></>}
 </section>
 {confirm&&<div className="modalBack" onClick={()=>setConfirm(null)}><div className="confirmModal" onClick={e=>e.stopPropagation()}><span>{confirm.kind==="archive"?"Delete account":"Reset password"}</span><h2>{confirm.user.name||confirm.user.uid}</h2><p>{confirm.kind==="archive"?"The account will be removed from active accounts and safely archived. Institutional history is preserved and the account can be restored later.":"A new temporary password will replace the current password. Share it securely with the account owner."}</p><div><button onClick={()=>setConfirm(null)}>Cancel</button><button className="danger" onClick={()=>confirm.kind==="archive"?void archive(confirm.user):void resetPassword(confirm.user)}>{confirm.kind==="archive"?"Delete account":"Generate temporary password"}</button></div></div></div>}
 </main>
}