"use client";
import {FormEvent,useEffect,useState} from "react";import {useRouter} from "next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL;
type Type="PROJECT"|"RESEARCH"|"EVENT"|"OPPORTUNITY";
type Item={id:number;type:Type;title:string;description?:string;category?:string;department?:string;linkUrl?:string;published:boolean};
export default function ContentManager(){const router=useRouter();const [items,setItems]=useState<Item[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const token=()=>sessionStorage.getItem("rkgitm_token")||"";
 useEffect(()=>{if(!sessionStorage.getItem("rkgitm_token"))router.replace("/login");else void load()},[]);
 async function load(){if(!API){setMsg("Connect the backend to manage live content.");return}const r=await fetch(API+"/api/content/admin",{headers:{Authorization:"Bearer "+token()}});if(r.status===401||r.status===403){router.replace("/login");return}if(r.ok)setItems(await r.json());else setMsg("Could not load content.");}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!API)return;setBusy(true);const fd=new FormData(e.currentTarget);const body={type:fd.get("type"),title:fd.get("title"),description:fd.get("description"),category:fd.get("category"),department:fd.get("department"),linkUrl:fd.get("linkUrl"),published:fd.get("published")==="on"};const r=await fetch(API+"/api/content/admin",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token()},body:JSON.stringify(body)});setBusy(false);if(r.ok){e.currentTarget.reset();setMsg("Content saved successfully.");await load()}else setMsg("Could not save content.");}
 async function remove(id:number){if(!API||!confirm("Delete this content item?"))return;const r=await fetch(API+"/api/content/admin/"+id,{method:"DELETE",headers:{Authorization:"Bearer "+token()}});if(r.ok)setItems(v=>v.filter(x=>x.id!==id));}
 async function toggle(x:Item){if(!API)return;const r=await fetch(API+"/api/content/admin/"+x.id,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token()},body:JSON.stringify({...x,published:!x.published})});if(r.ok)setItems(v=>v.map(i=>i.id===x.id?{...i,published:!i.published}:i));}
 return <main className="adminShell"><aside className="sideNav"><div className="brandMark">RA</div><div><strong>Achievement Hub</strong><small>Content Manager</small></div><nav><a href="/admin">Achievement Records</a><a className="active" href="/admin/content">Content Management</a><a href="/faculty">Verification Queue</a><a href="/">Public Website</a></nav></aside><section className="adminMain"><header className="adminTop"><div><p className="eyebrow">ADMIN CMS</p><h1>Publish campus content</h1><p>Create and manage projects, research, society events and opportunities.</p></div></header>
 <form className="cmsForm" onSubmit={create}><select name="type" required defaultValue="PROJECT"><option value="PROJECT">Project</option><option value="RESEARCH">Research</option><option value="EVENT">Society Event</option><option value="OPPORTUNITY">Opportunity</option></select><input name="title" required placeholder="Title"/><input name="category" placeholder="Category / Society name"/><input name="department" placeholder="Department / organizing society"/><input name="linkUrl" type="url" placeholder="External link (optional)"/><textarea name="description" required placeholder="Description"/><label className="publishCheck"><input type="checkbox" name="published"/> Publish immediately</label><button disabled={busy}>{busy?"Saving…":"Create content →"}</button></form>{msg&&<div className="adminNotice">{msg}</div>}
 <div className="cmsList">{items.map(x=><article key={x.id}><div><span className="cmsType">{x.type}</span><h2>{x.title}</h2><p>{x.description}</p><small>{x.department||"All departments"} • {x.published?"Published":"Draft"}</small></div><div className="cmsActions"><button onClick={()=>toggle(x)}>{x.published?"Unpublish":"Publish"}</button><button className="danger" onClick={()=>remove(x.id)}>Delete</button></div></article>)}</div></section></main>}