"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import NotificationBell from "../../components/NotificationBell";
const API=process.env.NEXT_PUBLIC_API_URL;
type R={id:number;collegeRollNo:string;universityRollNo?:string;name:string;department?:string;studyYear?:string;requestedRole:"STUDENT"|"FACULTY";status:"PENDING"|"APPROVED"|"REJECTED";generatedUserId?:string;rejectionReason?:string};
export default function IdentityReview(){
 const router=useRouter();const [items,setItems]=useState<R[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState<number|null>(null),[q,setQ]=useState(""),[status,setStatus]=useState("ALL"),[preview,setPreview]=useState<string|null>(null),[reject,setReject]=useState<R|null>(null),[reason,setReason]=useState("");
 const token=()=>sessionStorage.getItem("rkgitm_token")||"";
 useEffect(()=>{if(sessionStorage.getItem("rkgitm_role")!=="ADMIN"){router.replace("/login");return}void load()},[]);
 async function load(){if(!API){setMsg("Backend is not connected.");return}const r=await fetch(API+"/api/registration/review",{headers:{Authorization:"Bearer "+token()}});if(r.status===401||r.status===403){router.replace("/login");return}if(r.ok)setItems(await r.json());else setMsg("Could not load identity requests.");}
 async function decide(id:number,s:"APPROVED"|"REJECTED",why=""){if(!API)return;setBusy(id);const r=await fetch(API+`/api/registration/review/${id}?status=${s}${why?`&reason=${encodeURIComponent(why)}`:""}`,{method:"PATCH",headers:{Authorization:"Bearer "+token()}});setBusy(null);if(r.ok){const data=await r.json();setItems(v=>v.map(x=>x.id===id?{...x,status:s,generatedUserId:data.userId||x.generatedUserId,rejectionReason:why||x.rejectionReason}:x));setMsg(s==="APPROVED"?(data.userId?`Account activated. Faculty User ID: ${data.userId}`:"Account activated."):"Request rejected with feedback.");setReject(null);setReason("")}else setMsg("Could not update request.");}
 async function showCard(id:number){if(!API)return;const r=await fetch(API+`/api/registration/review/${id}/id-card`,{headers:{Authorization:"Bearer "+token()}});if(!r.ok){setMsg("Could not load ID card.");return}setPreview(URL.createObjectURL(await r.blob()))}
 const shown=useMemo(()=>items.filter(x=>(status==="ALL"||x.status===status)&&(x.name+" "+(x.department||"")+" "+x.status).toLowerCase().includes(q.toLowerCase())),[items,q,status]);
 return <main className="identityPro"><section className="identityInner">
  <header className="facultyHeader"><div><p className="eyebrow">IDENTITY CONTROL</p><h1>Campus Verification</h1><p>Validate faculty identity before granting institutional access.</p></div><div className="facultyHeaderActions"><NotificationBell/><a href="/admin">← Control Center</a></div></header>
  {msg&&<div className="adminNotice">{msg}</div>}
  <div className="identityStats"><article><span>Pending</span><strong>{items.filter(x=>x.status==="PENDING").length}</strong></article><article><span>Approved</span><strong>{items.filter(x=>x.status==="APPROVED").length}</strong></article><article><span>Rejected</span><strong>{items.filter(x=>x.status==="REJECTED").length}</strong></article></div>
  <div className="facultyFilters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search faculty or department…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All status</option><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></div>
  <div className="identityGrid">{shown.map(x=><article className="identityCard" key={x.id}><div className="reviewMeta"><span>{x.requestedRole}</span><span>{x.department||"Department not provided"}</span><span className={"statusPill "+x.status.toLowerCase()}>{x.status}</span></div><h2>{x.name}</h2><p>{x.requestedRole==="FACULTY"?"Faculty identity request":"Student identity request"}</p>{x.generatedUserId&&<div className="generatedFacultyId"><span>Faculty User ID</span><strong>{x.generatedUserId}</strong><button type="button" onClick={()=>navigator.clipboard.writeText(x.generatedUserId||"")}>Copy ID</button></div>}{x.rejectionReason&&<div className="rejectReason">Reason: {x.rejectionReason}</div>}<button className="proofBtn" type="button" onClick={()=>void showCard(x.id)}>Preview RKGITM ID card</button>{x.status==="PENDING"&&<div className="reviewActions"><button disabled={busy===x.id} onClick={()=>void decide(x.id,"APPROVED")}>Approve & Activate</button><button disabled={busy===x.id} className="reject" onClick={()=>setReject(x)}>Reject with reason</button></div>}</article>)}</div>
  {!shown.length&&<div className="facultyEmpty">No identity requests match this view.</div>}
 </section>
 {preview&&<div className="modalBack" onClick={()=>{URL.revokeObjectURL(preview);setPreview(null)}}><div className="docModal" onClick={e=>e.stopPropagation()}><header><strong>Submitted RKGITM ID Card</strong><button onClick={()=>{URL.revokeObjectURL(preview);setPreview(null)}}>×</button></header><img src={preview} alt="Submitted RKGITM ID card"/></div></div>}
 {reject&&<div className="modalBack" onClick={()=>setReject(null)}><div className="confirmModal rejectModal" onClick={e=>e.stopPropagation()}><span>REJECTION DECISION</span><h2>{reject.name}</h2><p>This reason will be visible to the applicant so they can correct and re-apply.</p><div className="quickReasons">{["ID card is unclear","Identity details do not match","Department information is incomplete","Invalid institutional ID"].map(x=><button key={x} className={reason===x?"on":""} onClick={()=>setReason(x)}>{x}</button>)}</div><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Write a custom reason…" rows={4}/><div><button onClick={()=>setReject(null)}>Cancel</button><button className="danger" disabled={!reason.trim()} onClick={()=>void decide(reject.id,"REJECTED",reason)}>Reject request</button></div></div></div>}
 </main>
}