package in.rkgitm.hub.achievement;
import in.rkgitm.hub.security.*;import in.rkgitm.hub.content.*;import org.springframework.http.ResponseEntity;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.time.Instant;import java.util.*;
@RestController @RequestMapping("/api/achievements")
public class AchievementController{
 private final AchievementRepository repo;private final ActivityService activity;private final ContentItemRepository content;
 public AchievementController(AchievementRepository repo,ActivityService activity,ContentItemRepository content){this.repo=repo;this.activity=activity;this.content=content;}
 @GetMapping("/public") public List<Achievement> approved(){return repo.findByStatusOrderByCreatedAtDesc(Achievement.Status.APPROVED);}
 @GetMapping("/pending") public List<Achievement> pending(){return repo.findByStatusOrderByCreatedAtDesc(Achievement.Status.PENDING);}
 @GetMapping("/faculty-summary") public Map<String,Object> facultySummary(){Map<String,Object> m=new LinkedHashMap<>();m.put("pending",repo.countByStatus(Achievement.Status.PENDING));m.put("approved",repo.countByStatus(Achievement.Status.APPROVED));m.put("rejected",repo.countByStatus(Achievement.Status.REJECTED));m.put("recent",repo.findAll().stream().sorted(Comparator.comparing(Achievement::getCreatedAt).reversed()).limit(8).toList());return m;}
 @GetMapping("/admin") public List<Achievement> admin(@RequestParam(required=false) Achievement.Status status){return status==null?repo.findAll():repo.findByStatusOrderByCreatedAtDesc(status);}
 @PostMapping public Achievement submit(@RequestBody Achievement a,Authentication auth){a.setStudentUid(auth.getName());a.setStatus(Achievement.Status.PENDING);Achievement saved=repo.save(a);activity.audit(auth.getName(),"ACHIEVEMENT_SUBMITTED","ACHIEVEMENT",String.valueOf(saved.getId()),saved.getTitle());return saved;}
 @PatchMapping("/{id}/status") public ResponseEntity<Achievement> status(@PathVariable Long id,@RequestParam Achievement.Status value,@RequestParam(required=false) String reason,Authentication auth){return repo.findById(id).map(a->{a.setStatus(value);a.setReviewedBy(auth.getName());a.setReviewedAt(Instant.now());a.setRejectionReason(value==Achievement.Status.REJECTED?(reason==null||reason.isBlank()?"Evidence or details require correction.":reason.trim()):null);Achievement saved=repo.save(a);if(value==Achievement.Status.APPROVED&&("PROJECT".equalsIgnoreCase(a.getCategory())||"RESEARCH".equalsIgnoreCase(a.getCategory()))){ContentItem item=new ContentItem();item.setType("PROJECT".equalsIgnoreCase(a.getCategory())?ContentItem.Type.PROJECT:ContentItem.Type.RESEARCH);item.setTitle(a.getTitle());item.setDescription(a.getDescription());item.setCategory(a.getCategory());item.setDepartment(a.getDepartment());item.setLinkUrl(a.getProofUrl());item.setPublished(true);content.save(item);}activity.audit(auth.getName(),"ACHIEVEMENT_"+value.name(),"ACHIEVEMENT",String.valueOf(id),a.getTitle());activity.notify(a.getStudentUid(),value==Achievement.Status.APPROVED?"Achievement approved":"Achievement needs changes",value==Achievement.Status.APPROVED?a.getTitle()+" is now verified and public.":a.getTitle()+" was rejected: "+a.getRejectionReason(),"/student");return ResponseEntity.ok(saved);}).orElse(ResponseEntity.notFound().build());}
}