package in.rkgitm.hub.achievement;
import in.rkgitm.hub.security.*;import org.springframework.http.ResponseEntity;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController
public class StudentProfileController{
 private final PortalUserRepository users;private final AchievementRepository achievements;private final ActivityService activity;
 public StudentProfileController(PortalUserRepository u,AchievementRepository a,ActivityService activity){users=u;achievements=a;this.activity=activity;}
 private int points(Achievement a){if(a.getStatus()!=Achievement.Status.APPROVED)return 0;String c=Optional.ofNullable(a.getCategory()).orElse("").toLowerCase();if(c.contains("research")||c.contains("publication")||c.contains("patent"))return 250;if(c.contains("project")||c.contains("innovation"))return 180;if(c.contains("hackathon")||c.contains("competition")||c.contains("award"))return 150;if(c.contains("certif"))return 80;return 100;}
 @GetMapping("/api/profile/{uid}") public ResponseEntity<?> publicProfile(@PathVariable String uid){return users.findByUid(uid).filter(u->u.getRole()==PortalUser.Role.STUDENT&&!u.isArchived()&&u.isActive()).map(u->{List<Achievement> approved=achievements.findByStudentUidOrderByCreatedAtDesc(uid).stream().filter(a->a.getStatus()==Achievement.Status.APPROVED).toList();Map<String,Object> m=new LinkedHashMap<>();m.put("uid",u.getUid());m.put("name",u.getName());m.put("department",u.getDepartment());m.put("studyYear",u.getStudyYear());m.put("photoUrl",u.getPhotoUrl());m.put("score",approved.stream().mapToInt(this::points).sum());m.put("verified",approved.size());m.put("achievements",approved);return ResponseEntity.ok(m);}).orElse(ResponseEntity.notFound().build());}
 public record ProfileUpdate(String name,String studyYear,String photoUrl){}
 @PatchMapping("/api/student/profile") public ResponseEntity<?> update(@RequestBody ProfileUpdate in,Authentication auth){PortalUser u=users.findByUid(auth.getName()).orElseThrow();if(in.name()!=null&&!in.name().isBlank())u.setName(in.name().trim());if(in.studyYear()!=null)u.setStudyYear(in.studyYear().trim());if(in.photoUrl()!=null)u.setPhotoUrl(in.photoUrl().trim());users.save(u);activity.audit(auth.getName(),"PROFILE_UPDATED","USER",u.getUid(),"Student profile updated");return ResponseEntity.ok(Map.of("ok",true));}
}