package in.rkgitm.hub.security;
import org.springframework.http.*;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.io.IOException;import java.util.*;
@RestController @RequestMapping("/api/registration") public class RegistrationController{
 private final RegistrationRequestRepository requests;private final PortalUserRepository users;private final BCryptPasswordEncoder encoder=new BCryptPasswordEncoder();
 public RegistrationController(RegistrationRequestRepository r,PortalUserRepository u){requests=r;users=u;}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<?> register(@RequestParam String collegeRollNo,@RequestParam(required=false) String universityRollNo,@RequestParam String name,@RequestParam String department,@RequestParam(required=false) String studyYear,@RequestParam RegistrationRequest.RequestedRole requestedRole,@RequestParam String password,@RequestParam MultipartFile idCard)throws IOException{
  if(requests.existsByCollegeRollNo(collegeRollNo)||users.existsByUid(collegeRollNo))return ResponseEntity.status(409).body(Map.of("error","A request/account already exists for this college roll number."));
  if(idCard.isEmpty()||idCard.getContentType()==null||!idCard.getContentType().startsWith("image/"))return ResponseEntity.badRequest().body(Map.of("error","A college ID card image is required."));
  if(idCard.getSize()>5_000_000)return ResponseEntity.badRequest().body(Map.of("error","ID card image must be under 5 MB."));
  if(requestedRole==RegistrationRequest.RequestedRole.STUDENT&&(universityRollNo==null||universityRollNo.isBlank()||studyYear==null||studyYear.isBlank()))return ResponseEntity.badRequest().body(Map.of("error","University roll number and study year are required for students."));
  RegistrationRequest x=new RegistrationRequest();x.setCollegeRollNo(collegeRollNo);x.setUniversityRollNo(universityRollNo);x.setName(name);x.setDepartment(department);x.setStudyYear(studyYear);x.setRequestedRole(requestedRole);x.setPasswordHash(encoder.encode(password));x.setIdCardFileName(idCard.getOriginalFilename());x.setIdCardContentType(idCard.getContentType());x.setIdCardImage(idCard.getBytes());requests.save(x);return ResponseEntity.status(201).body(Map.of("status","PENDING","message","Identity submitted for RKGITM verification."));
 }
 @GetMapping("/admin") public List<Map<String,Object>> pending(){return requests.findAllByOrderByCreatedAtDesc().stream().map(x->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",x.getId());m.put("collegeRollNo",x.getCollegeRollNo());m.put("universityRollNo",x.getUniversityRollNo());m.put("name",x.getName());m.put("department",x.getDepartment());m.put("studyYear",x.getStudyYear());m.put("requestedRole",x.getRequestedRole());m.put("status",x.getStatus());return m;}).toList();}
 @GetMapping("/admin/{id}/id-card") public ResponseEntity<byte[]> card(@PathVariable Long id){return requests.findById(id).map(x->ResponseEntity.ok().contentType(MediaType.parseMediaType(x.getIdCardContentType())).body(x.getIdCardImage())).orElse(ResponseEntity.notFound().build());}
 @PatchMapping("/admin/{id}") public ResponseEntity<?> decide(@PathVariable Long id,@RequestParam RegistrationRequest.Status status){return requests.findById(id).map(x->{x.setStatus(status);requests.save(x);if(status==RegistrationRequest.Status.APPROVED&&!users.existsByUid(x.getCollegeRollNo())){PortalUser u=new PortalUser();u.setUid(x.getCollegeRollNo());u.setPasswordHash(x.getPasswordHash());u.setName(x.getName());u.setDepartment(x.getDepartment());u.setRole(x.getRequestedRole()==RegistrationRequest.RequestedRole.FACULTY?PortalUser.Role.FACULTY:PortalUser.Role.STUDENT);users.save(u);}return ResponseEntity.ok(Map.of("status",status));}).orElse(ResponseEntity.notFound().build());}
}