package in.rkgitm.hub.security;
import org.springframework.http.*;import org.springframework.security.core.*;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.io.IOException;import java.util.*;
@RestController @RequestMapping("/api/registration") public class RegistrationController{
 private final RegistrationRequestRepository requests;private final PortalUserRepository users;private final BCryptPasswordEncoder encoder=new BCryptPasswordEncoder();
 public RegistrationController(RegistrationRequestRepository r,PortalUserRepository u){requests=r;users=u;}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<?> register(@RequestParam String collegeRollNo,@RequestParam(required=false) String universityRollNo,@RequestParam String name,@RequestParam String department,@RequestParam(required=false) String studyYear,@RequestParam RegistrationRequest.RequestedRole requestedRole,@RequestParam String password,@RequestParam MultipartFile idCard)throws IOException{
  if(requestedRole==RegistrationRequest.RequestedRole.FACULTY){collegeRollNo="FAC-REQ-"+UUID.randomUUID();}else if(requests.existsByCollegeRollNo(collegeRollNo)||users.existsByUid(collegeRollNo))return ResponseEntity.status(409).body(Map.of("error","A request/account already exists for this UID."));
  if(idCard.isEmpty()||idCard.getContentType()==null||!idCard.getContentType().startsWith("image/"))return ResponseEntity.badRequest().body(Map.of("error","A college ID card image is required."));
  if(idCard.getSize()>5_000_000)return ResponseEntity.badRequest().body(Map.of("error","ID card image must be under 5 MB."));
  if(requestedRole==RegistrationRequest.RequestedRole.STUDENT&&(universityRollNo==null||universityRollNo.isBlank()||studyYear==null||studyYear.isBlank()))return ResponseEntity.badRequest().body(Map.of("error","University roll number and study year are required for students."));
  RegistrationRequest x=new RegistrationRequest();x.setCollegeRollNo(collegeRollNo);x.setUniversityRollNo(universityRollNo);x.setName(name);x.setDepartment(department);x.setStudyYear(studyYear);x.setRequestedRole(requestedRole);x.setPasswordHash(encoder.encode(password));x.setIdCardFileName(idCard.getOriginalFilename());x.setIdCardContentType(idCard.getContentType());x.setIdCardImage(idCard.getBytes());requests.save(x);return ResponseEntity.status(201).body(Map.of("status","PENDING","message",requestedRole==RegistrationRequest.RequestedRole.FACULTY?"Awaiting Super Admin approval.":"Awaiting Faculty approval."));
 }
 private boolean admin(Authentication a){return a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN"));}
 private PortalUser actor(Authentication a){return users.findByUid(a.getName()).orElse(null);}
 @GetMapping("/review") public List<Map<String,Object>> review(Authentication a){boolean root=admin(a);PortalUser me=actor(a);return requests.findAllByOrderByCreatedAtDesc().stream().filter(x->root?x.getRequestedRole()==RegistrationRequest.RequestedRole.FACULTY:x.getRequestedRole()==RegistrationRequest.RequestedRole.STUDENT&&me!=null&&Objects.equals(me.getDepartment(),x.getDepartment())).map(x->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",x.getId());m.put("collegeRollNo",x.getCollegeRollNo());m.put("universityRollNo",x.getUniversityRollNo());m.put("name",x.getName());m.put("department",x.getDepartment());m.put("studyYear",x.getStudyYear());m.put("requestedRole",x.getRequestedRole());m.put("status",x.getStatus());return m;}).toList();}
 @GetMapping("/review/{id}/id-card") public ResponseEntity<byte[]> card(@PathVariable Long id,Authentication a){return requests.findById(id).filter(x->admin(a)?x.getRequestedRole()==RegistrationRequest.RequestedRole.FACULTY:x.getRequestedRole()==RegistrationRequest.RequestedRole.STUDENT&&actor(a)!=null&&Objects.equals(actor(a).getDepartment(),x.getDepartment())).map(x->ResponseEntity.ok().contentType(MediaType.parseMediaType(x.getIdCardContentType())).body(x.getIdCardImage())).orElse(ResponseEntity.notFound().build());}
 @PatchMapping("/review/{id}") public ResponseEntity<?> decide(@PathVariable Long id,@RequestParam RegistrationRequest.Status status,Authentication a){return requests.findById(id).map(x->{PortalUser me=actor(a);boolean allowed=admin(a)?x.getRequestedRole()==RegistrationRequest.RequestedRole.FACULTY:x.getRequestedRole()==RegistrationRequest.RequestedRole.STUDENT&&me!=null&&Objects.equals(me.getDepartment(),x.getDepartment());if(!allowed)return ResponseEntity.status(403).body(Map.of("error","Not authorized for this identity."));x.setStatus(status);requests.save(x);if(status==RegistrationRequest.Status.APPROVED){String approvedUid=x.getCollegeRollNo();if(x.getRequestedRole()==RegistrationRequest.RequestedRole.FACULTY)approvedUid=String.format("RKG-FAC-%04d",x.getId());if(!users.existsByUid(approvedUid)){PortalUser u=new PortalUser();u.setUid(approvedUid);u.setPasswordHash(x.getPasswordHash());u.setName(x.getName());u.setDepartment(x.getDepartment());u.setRole(x.getRequestedRole()==RegistrationRequest.RequestedRole.FACULTY?PortalUser.Role.FACULTY:PortalUser.Role.STUDENT);users.save(u);}return ResponseEntity.ok(Map.of("status",status,"userId",approvedUid));}return ResponseEntity.ok(Map.of("status",status));}).orElse(ResponseEntity.notFound().build());}
}