"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL;
type Status={status:"PENDING"|"APPROVED"|"REJECTED";rejectionReason?:string;universityRollNo?:string};
export default function StudentAccess(){
 const router=useRouter();const [mode,setMode]=useState<"create"|"login">("create"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState<Status|null>(null);
 async function createAccount(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setMsg("");const form=e.currentTarget,fd=new FormData(form);const password=String(fd.get("password")||""),confirm=String(fd.get("confirmPassword")||""),roll=String(fd.get("universityRollNo")||"").trim();if(password!==confirm){setMsg("Password and Confirm Password do not match.");return}if(!API){setMsg("Registration service is unavailable.");return}setBusy(true);
  const payload=new FormData();payload.set("collegeRollNo",roll);payload.set("universityRollNo",roll);payload.set("name",String(fd.get("name")||"").trim());payload.set("department",String(fd.get("department")||"").trim());payload.set("studyYear",String(fd.get("studyYear")||"").trim());payload.set("requestedRole","STUDENT");payload.set("password",password);const card=fd.get("idCard");if(card instanceof File)payload.set("idCard",card);
  try{const r=await fetch(API+"/api/registration",{method:"POST",body:payload});const data=await r.json();if(!r.ok)throw new Error(data.error||"Registration failed.");localStorage.setItem("rkgitm_student_request_id",String(data.id));setStatus({status:"PENDING",universityRollNo:roll});setMsg(data.resubmitted?"Corrected request resubmitted for faculty verification.":"Registration submitted for faculty verification.");form.reset()}catch(err){setMsg(err instanceof Error?err.message:"Registration failed.");}finally{setBusy(false)}
 }
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setMsg("");if(!API){setMsg("Login service is unavailable.");return}setBusy(true);const fd=new FormData(e.currentTarget);try{const r=await fetch(API+"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:fd.get("username"),password:fd.get("password")})});if(!r.ok)throw new Error();const data=await r.json();if(data.role!=="STUDENT")throw new Error();localStorage.setItem("rkgitm_token",data.token);localStorage.setItem("rkgitm_role",data.role);localStorage.setItem("rkgitm_uid",data.uid||"");router.replace("/student")}catch{setMsg("Invalid Student User ID/password, or your RKGITM verification is still pending.")}finally{setBusy(false)}
 }
 return <main className="loginPage"><a href="/" className="backLink">← RKGITM Achievement Hub</a><section className="loginCard"><div className="loginBrand"><span>RA</span><div><strong>Student Portal</strong><small>RKGITM Achievement Hub</small></div></div><p className="eyebrow">STUDENT ACCESS</p><h1>{mode==="create"?"Create your":"Welcome back to"}<br/><em>RKGITM account.</em></h1>
  {status&&<div className={"studentRequestStatus "+status.status.toLowerCase()}><strong>{status.status==="PENDING"?"Verification in progress":status.status==="APPROVED"?"Account approved":"Verification needs correction"}</strong>{status.status==="PENDING"&&<p>Your RKGITM ID and profile details are waiting for faculty review.</p>}{status.status==="APPROVED"&&<p>Your User ID is your University Roll Number. You can login now.</p>}{status.status==="REJECTED"&&<><p>Reason: {status.rejectionReason||"Details need correction."}</p><small>Update the form below and resubmit with a clear ID card.</small></>}</div>}
  <div className="studentAccessTabs"><button type="button" className={mode==="create"?"studentAccessTab active":"studentAccessTab"} onClick={()=>{setMode("create");setMsg("")}}>Create Account</button><button type="button" className={mode==="login"?"studentAccessTab active":"studentAccessTab"} onClick={()=>{setMode("login");setMsg("")}}>Login</button></div>
  {mode==="create"?<form onSubmit={createAccount}><label>Full Name<input name="name" required minLength={2} placeholder="Student full name"/></label><label>University Roll Number<input name="universityRollNo" required autoComplete="username" placeholder="Enter university roll number"/></label><div className="two"><label>Department<select name="department" required><option value="">Select department</option><option>CSE</option><option>IT</option><option>ECE</option><option>EEE</option><option>ME</option><option>CE</option><option>MBA</option></select></label><label>Study Year<select name="studyYear" required><option value="">Select year</option><option>1st Year</option><option>2nd Year</option><option>3rd Year</option><option>4th Year</option></select></label></div><label>RKGITM College ID Card<input name="idCard" type="file" accept="image/*" required/></label><small className="secureNote">Upload a clear RKGITM college ID card. Maximum 5 MB.</small><label>Password<input name="password" type="password" minLength={8} required autoComplete="new-password" placeholder="Minimum 8 characters"/></label><label>Confirm Password<input name="confirmPassword" type="password" minLength={8} required autoComplete="new-password" placeholder="Re-enter password"/></label><button disabled={busy}>{busy?"Submitting…":"Submit for Verification →"}</button></form>:<form onSubmit={login}><label>User ID<input name="username" required autoComplete="username" placeholder="University Roll Number"/></label><label>Password<input name="password" type="password" required autoComplete="current-password" placeholder="••••••••"/></label><button disabled={busy}>{busy?"Signing in…":"Login →"}</button></form>}
  {msg&&<p className="notice" role="status">{msg}</p>}</section></main>
}



