spring.application.name=rkgitm-achievement-hub
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/rkgitm_hub}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.port=${PORT:8080}
