"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL;
type A={id:number;title:string;studentName:string;department?:string;category?:string;description?:string;proofUrl?:string;status:string;rejectionReason?:string;reviewedBy?:string;reviewedAt?:string;createdAt:string};
type R={id:number;collegeRollNo:string;universityRollNo?:string;name:string;department:string;studyYear?:string;status:string;rejectionReason?:string};
type Summary={pending:number;approved:number;rejected:number;recent:A[]};
export default function Faculty(){
 const router=useRouter();const [items,setItems]=useState<A[]>([]),[registrations,setRegistrations]=useState<R[]>([]),[summary,setSummary]=useState<Summary>({pending:0,approved:0,rejected:0,recent:[]}),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[status,setStatus]=useState("PENDING"),[category,setCategory]=useState("ALL"),[reject,setReject]=useState<{kind:"achievement"|"registration";id:number;name:string}|null>(null),[reason,setReason]=useState(""),[preview,setPreview]=useState<string|null>(null);
 const token=()=>typeof window==="undefined"?"":localStorage.getItem("rkgitm_token")||sessionStorage.getItem("rkgitm_token")||"";
 useEffect(()=>{const role=localStorage.getItem("rkgitm_role")||sessionStorage.getItem("rkgitm_role");if(role!=="FACULTY"){router.replace("/login");return}void load()},[]);
 useEffect(()=>{if(!msg)return;const t=window.setTimeout(()=>setMsg(""),3500);return()=>window.clearTimeout(t)},[msg]);
 async function refreshToken(){const rt=localStorage.getItem("rkgitm_refresh_token");if(!API||!rt)return false;const r=await fetch(API+"/api/auth/refresh",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({refreshToken:rt})});if(!r.ok)return false;const x=await r.json();if(x.role!=="FACULTY")return false;localStorage.setItem("rkgitm_token",x.token);if(x.refreshToken)localStorage.setItem("rkgitm_refresh_token",x.refreshToken);localStorage.setItem("rkgitm_role",x.role);return true}
 async function load(){if(!API){setMsg("Verification service is unavailable.");setLoading(false);return}try{const h={Authorization:"Bearer "+token()};let [a,r,s]=await Promise.all([fetch(API+"/api/achievements/admin",{headers:h}),fetch(API+"/api/registration/review",{headers:h}),fetch(API+"/api/achievements/faculty-summary",{headers:h})]);if((a.status===401||a.status===403)&&await refreshToken()){const nh={Authorization:"Bearer "+token()};[a,r,s]=await Promise.all([fetch(API+"/api/achievements/admin",{headers:nh}),fetch(API+"/api/registration/review",{headers:nh}),fetch(API+"/api/achievements/faculty-summary",{headers:nh})])}if(a.status===401||a.status===403){localStorage.removeItem("rkgitm_token");localStorage.removeItem("rkgitm_refresh_token");localStorage.removeItem("rkgitm_role");router.replace("/login");return}if(a.ok)setItems(await a.json());if(r.ok)setRegistrations(await r.json());if(s.ok)setSummary(await s.json())}catch{setMsg("Verification service is currently unavailable.")}finally{setLoading(false)}}
 async function decideAchievement(id:number,value:"APPROVED"|"REJECTED",why=""){if(!API)return;const r=await fetch(API+`/api/achievements/${id}/status?value=${value}${why?`&reason=${encodeURIComponent(why)}`:""}`,{method:"PATCH",headers:{Authorization:"Bearer "+token()}});if(r.ok){setMsg(value==="APPROVED"?"Achievement approved and published.":"Achievement rejected with feedback.");setReject(null);setReason("");void load()}}
 async function decideRegistration(id:number,value:"APPROVED"|"REJECTED",why=""){if(!API)return;const r=await fetch(API+`/api/registration/review/${id}?status=${value}${why?`&reason=${encodeURIComponent(why)}`:""}`,{method:"PATCH",headers:{Authorization:"Bearer "+token()}});if(r.ok){setMsg(value==="APPROVED"?"Student account approved.":"Student request rejected with reason.");setReject(null);setReason("");void load()}}
 async function showCard(id:number){if(!API)return;const r=await fetch(API+`/api/registration/review/${id}/id-card`,{headers:{Authorization:"Bearer "+token()}});if(!r.ok){setMsg("Could not load submitted ID card.");return}const url=URL.createObjectURL(await r.blob());setPreview(url)}
 const categories=useMemo(()=>Array.from(new Set(items.map(x=>x.category).filter(Boolean) as string[])).sort(),[items]);
 const shown=useMemo(()=>items.filter(a=>(status==="ALL"||a.status===status)&&(category==="ALL"||a.category===category)&&(a.title+" "+a.studentName+" "+(a.department||"")+" "+(a.category||"")).toLowerCase().includes(query.toLowerCase())),[items,query,status,category]);
 const pendingRegs=registrations.filter(x=>x.status==="PENDING"),historyRegs=registrations.filter(x=>x.status!=="PENDING");
 function ago(v?:string){if(!v)return"";const h=Math.floor((Date.now()-new Date(v).getTime())/3600000);return h<1?"Just now":h<24?h+"h ago":Math.floor(h/24)+"d ago"}
 function exportCsv(){const rows=[["Student","Title","Department","Category","Status","Reviewer","Reviewed At"],...shown.map(x=>[x.studentName,x.title,x.department||"",x.category||"",x.status,x.reviewedBy||"",x.reviewedAt||""])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="faculty-verification-report.csv";a.click();URL.revokeObjectURL(url)}
 return <main className="facultyPro"><section className="facultyInner">
  <header className="facultyHeader"><div><p className="eyebrow">FACULTY CONSOLE</p><h1>Verification Workspace</h1><p>Review student identities, evidence and institutional records from one queue.</p></div><div className="facultyHeaderActions"><a href="/achievements">Published records ↗</a><a href="/account/security">Security</a><button onClick={()=>{localStorage.removeItem("rkgitm_token");localStorage.removeItem("rkgitm_refresh_token");localStorage.removeItem("rkgitm_role");localStorage.removeItem("rkgitm_uid");sessionStorage.clear();router.replace("/login")}}>Sign out</button></div></header>
  {msg&&<div className="adminNotice">{msg}</div>}
  {loading?<div className="saSkeleton"><i/><i/><i/></div>:<>
  <section className="facultyStats"><article><span>Pending achievements</span><strong>{summary.pending}</strong><small>Needs verification</small></article><article><span>Approved</span><strong>{summary.approved}</strong><small>Verified records</small></article><article><span>Rejected</span><strong>{summary.rejected}</strong><small>Returned with feedback</small></article><article><span>Student access</span><strong>{pendingRegs.length}</strong><small>Pending account requests</small></article></section>
  <section className="facultyPanel"><div className="facultyPanelHead"><div><p className="eyebrow">STUDENT ACCESS</p><h2>Pending account requests</h2></div><span>{pendingRegs.length} pending</span></div>
   <div className="facultyCards">{pendingRegs.map(r=><article key={r.id}><div className="reviewMeta"><span>{r.department}</span><span>{r.studyYear||"Student"}</span></div><h3>{r.name}</h3><p>College UID: <b>{r.collegeRollNo}</b>{r.universityRollNo&&<> • University: <b>{r.universityRollNo}</b></>}</p><button className="proofBtn" onClick={()=>void showCard(r.id)}>Preview submitted ID card</button><div className="reviewActions"><button onClick={()=>void decideRegistration(r.id,"APPROVED")}>Approve student</button><button className="reject" onClick={()=>setReject({kind:"registration",id:r.id,name:r.name})}>Reject with reason</button></div></article>)}{!pendingRegs.length&&<div className="facultyEmpty">✓ No pending student account requests.</div>}</div>
  </section>
  <section className="facultyPanel"><div className="facultyPanelHead"><div><p className="eyebrow">ACHIEVEMENT REVIEW</p><h2>Submission directory</h2></div><div className="saReportBtns"><button onClick={exportCsv}>Export CSV</button><button onClick={()=>window.print()}>Print / PDF</button></div></div>
   <div className="facultyFilters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search student, title, department…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option><option value="ALL">All status</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="ALL">All categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div>
   <div className="facultyCards">{shown.map(a=><article key={a.id}><div className="reviewMeta"><span>{a.category||"Achievement"}</span><span>{a.department||"Department not provided"}</span><span className={"statusPill "+a.status.toLowerCase()}>{a.status}</span></div><h3>{a.title}</h3><strong>{a.studentName}</strong><p>{a.description}</p>{a.proofUrl&&<a className="proofBtn" href={a.proofUrl} target="_blank" rel="noreferrer">Preview supporting evidence ↗</a>}{a.rejectionReason&&<div className="rejectReason">Feedback: {a.rejectionReason}</div>}<small className="activityTime">Submitted {ago(a.createdAt)} {a.reviewedBy&&"• Reviewed by "+a.reviewedBy}</small>{a.status==="PENDING"&&<div className="reviewActions"><button onClick={()=>void decideAchievement(a.id,"APPROVED")}>Approve record</button><button className="reject" onClick={()=>setReject({kind:"achievement",id:a.id,name:a.title})}>Reject with reason</button></div>}</article>)}{!shown.length&&<div className="facultyEmpty">No records match these filters.</div>}</div>
  </section>
  <section className="facultyPanel"><div className="facultyPanelHead"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Review history</h2></div></div><div className="historyList">{summary.recent?.map(x=><article key={x.id}><span className={"statusPill "+x.status.toLowerCase()}>{x.status}</span><div><strong>{x.title}</strong><small>{x.studentName} • {x.category||"Achievement"}</small></div><time>{ago(x.reviewedAt||x.createdAt)}</time></article>)}{historyRegs.slice(0,4).map(x=><article key={"r"+x.id}><span className={"statusPill "+x.status.toLowerCase()}>{x.status}</span><div><strong>{x.name}</strong><small>Student account • {x.department}</small></div></article>)}</div></section></>}
 </section>
 {preview&&<div className="modalBack" onClick={()=>{URL.revokeObjectURL(preview);setPreview(null)}}><div className="docModal" onClick={e=>e.stopPropagation()}><header><strong>Submitted RKGITM ID Card</strong><button onClick={()=>{URL.revokeObjectURL(preview);setPreview(null)}}>×</button></header><img src={preview} alt="Submitted ID card"/></div></div>}
 {reject&&<div className="modalBack" onClick={()=>setReject(null)}><div className="confirmModal rejectModal" onClick={e=>e.stopPropagation()}><span>REJECTION FEEDBACK</span><h2>{reject.name}</h2><p>Select a clear reason. The student will see this feedback and can correct the submission.</p><div className="quickReasons">{["ID / evidence is unclear","Details do not match evidence","Incomplete information","Duplicate submission"].map(x=><button key={x} className={reason===x?"on":""} onClick={()=>setReason(x)}>{x}</button>)}</div><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Or write a custom reason…" rows={4}/><div><button onClick={()=>setReject(null)}>Cancel</button><button className="danger" disabled={!reason.trim()} onClick={()=>reject.kind==="achievement"?void decideAchievement(reject.id,"REJECTED",reason):void decideRegistration(reject.id,"REJECTED",reason)}>Reject & send feedback</button></div></div></div>}
 </main>
}