"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL;
type A={id:number;title:string;studentName:string;department?:string;category?:string;description?:string;proofUrl?:string};
type R={id:number;collegeRollNo:string;universityRollNo?:string;name:string;department:string;studyYear?:string;status:string};
export default function Faculty(){ const router=useRouter();
 const [items,setItems]=useState<A[]>([]),[registrations,setRegistrations]=useState<R[]>([]),[summary,setSummary]=useState({pending:0,approved:0,rejected:0}),[msg,setMsg]=useState(""),[query,setQuery]=useState("");
 function token(){return typeof window==="undefined"?"":sessionStorage.getItem("rkgitm_token")||""}
 useEffect(()=>{if(typeof window!=="undefined"&&!sessionStorage.getItem("rkgitm_token"))router.replace("/login")},[router]);
 async function load(){if(!API){setMsg("Preview mode — connect the deployed backend to load live submissions.");return}try{const r=await fetch(API+"/api/achievements/pending",{headers:{Authorization:"Bearer "+token()}});if(r.status===401||r.status===403){sessionStorage.removeItem("rkgitm_token");router.replace("/login");return}if(!r.ok)throw new Error();setItems(await r.json());const rr=await fetch(API+"/api/registration/review",{headers:{Authorization:"Bearer "+token()}});if(rr.ok)setRegistrations(await rr.json());const sr=await fetch(API+"/api/achievements/faculty-summary",{headers:{Authorization:"Bearer "+token()}});if(sr.ok)setSummary(await sr.json())}catch{setMsg("Verification service is currently unavailable.")}}
 useEffect(()=>{void load()},[]);
 async function decide(id:number,value:"APPROVED"|"REJECTED"){if(!API)return;await fetch(API+`/api/achievements/${id}/status?value=${value}`,{method:"PATCH",headers:{Authorization:"Bearer "+token()}});setItems(v=>v.filter(x=>x.id!==id));void load()}
 async function decideRegistration(id:number,status:"APPROVED"|"REJECTED"){if(!API)return;const r=await fetch(API+`/api/registration/review/${id}?status=${status}`,{method:"PATCH",headers:{Authorization:"Bearer "+token()}});if(r.ok){setRegistrations(v=>v.filter(x=>x.id!==id));void load()}}
 const shown=useMemo(()=>items.filter(a=>(a.title+" "+a.studentName+" "+(a.department||"")+" "+(a.category||"")).toLowerCase().includes(query.toLowerCase())),[items,query]);
 return <main className="adminShell"><aside className="sideNav"><div className="brandMark">RA</div><div><strong>Achievement Hub</strong><small>Faculty Console</small></div><nav><a className="active" href="/faculty">Verification Queue</a><a href="/achievements">Published Records</a><a href="/">Public Website</a></nav><div className="sideFoot">RKGITM • Internal MVP</div></aside>
 <section className="adminMain"><header className="adminTop"><div><p className="eyebrow">FACULTY CONSOLE</p><h1>Verification Queue</h1><p>Review evidence before achievements become part of the public institutional record.</p></div><div className="topActions"><div className="adminBadge">Reviewer</div><button className="logoutBtn" onClick={()=>{sessionStorage.removeItem("rkgitm_token");router.replace("/login")}}>Sign out</button></div></header>
 <div className="statRow"><div><span>Pending approvals</span><strong>{summary.pending}</strong></div><div><span>Approved</span><strong>{summary.approved}</strong></div><div><span>Rejected</span><strong>{summary.rejected}</strong></div></div>
 <h2 style={{fontSize:28,marginTop:36}}>Student account requests</h2>
 <div className="reviewList">{registrations.map(r=><article className="reviewCard" key={"reg"+r.id}><div className="reviewMeta"><span>{r.department}</span><span>{r.studyYear||"Student"}</span></div><h2>{r.name}</h2><strong>{r.collegeRollNo}</strong>{r.universityRollNo&&<p>University Roll No: {r.universityRollNo}</p>}<div className="reviewActions"><button onClick={()=>decideRegistration(r.id,"APPROVED")}>Approve student</button><button className="reject" onClick={()=>decideRegistration(r.id,"REJECTED")}>Reject</button></div></article>)}</div>
 <div className="toolbar"><input aria-label="Search submissions" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search student, title, department…"/><span>{shown.length} submission{shown.length===1?"":"s"}</span></div>
 {msg&&<div className="adminNotice">{msg}</div>}<div className="reviewList">{shown.map(a=><article className="reviewCard" key={a.id}><div className="reviewMeta"><span>{a.category||"Achievement"}</span><span>{a.department||"Department not provided"}</span></div><h2>{a.title}</h2><strong>{a.studentName}</strong><p>{a.description}</p>{a.proofUrl&&<a className="proof" href={a.proofUrl} target="_blank" rel="noreferrer">View supporting evidence ↗</a>}<div className="reviewActions"><button onClick={()=>decide(a.id,"APPROVED")}>Approve record</button><button className="reject" onClick={()=>decide(a.id,"REJECTED")}>Reject</button></div></article>)}</div>
 {shown.length===0&&!msg&&<div className="adminEmpty"><span>✓</span><h2>Queue is clear.</h2><p>No submissions currently match this view.</p></div>}</section></main>
}