"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL;
type Post={id:number;title:string;category?:string;status:string;rejectionReason?:string;createdAt?:string};
type Row={rank:number;uid:string;name:string;department?:string;verified:number;score:number};
type D={name?:string;uid:string;department?:string;studyYear?:string;photoUrl?:string;lastActiveAt?:string;profileStrength:number;score:number;rank:number;totalPosts:number;approved:number;pending:number;rejected:number;posts:Post[];leaderboard:Row[];departmentLeaderboard:Row[];badge:string;nextMilestone:number;pointsToNext:number};
export default function StudentDashboard(){
 const router=useRouter();const [d,setD]=useState<D|null>(null),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[edit,setEdit]=useState(false),[name,setName]=useState(""),[year,setYear]=useState(""),[photo,setPhoto]=useState("");
 const token=()=>typeof window==="undefined"?"":sessionStorage.getItem("rkgitm_token")||"";
 async function load(){if(!API){setMsg("Dashboard service is not connected.");setLoading(false);return}try{const r=await fetch(API+"/api/student/dashboard",{headers:{Authorization:"Bearer "+token()}});if(!r.ok)throw new Error();const x=await r.json();setD(x);setName(x.name||"");setYear(x.studyYear||"");setPhoto(x.photoUrl||"")}catch{setMsg("Could not load your dashboard.")}finally{setLoading(false)}}
 useEffect(()=>{if(sessionStorage.getItem("rkgitm_role")!=="STUDENT"){router.replace("/login");return}void load()},[]);
 useEffect(()=>{if(!msg)return;const t=window.setTimeout(()=>setMsg(""),3500);return()=>window.clearTimeout(t)},[msg]);
 async function saveProfile(){if(!API)return;const r=await fetch(API+"/api/student/profile",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token()},body:JSON.stringify({name,studyYear:year,photoUrl:photo})});if(r.ok){setEdit(false);setMsg("Profile updated successfully.");void load()}else setMsg("Could not update profile.")}
 return <main className="studentDash"><header className="studentTop"><div className="studentIdentity">{d?.photoUrl?<img src={d.photoUrl} alt="Profile"/>:<span>{(d?.name||"S").slice(0,1).toUpperCase()}</span>}<div><p className="eyebrow">MY RKGITM PROFILE</p><h1>{d?.name||"Student Dashboard"}</h1><p>{d?.department} {d?.studyYear&&"• "+d.studyYear} {d?.uid&&"• "+d.uid}</p></div></div><div className="studentActions"><a className="secondary" href={d?.uid?`/profile/${encodeURIComponent(d.uid)}`:"#"}>Public profile</a><button onClick={()=>setEdit(true)}>Edit profile</button><a className="secondary" href="/account/security">Security</a><a className="primary" href="/submit">+ Submit Work</a><button onClick={()=>{sessionStorage.clear();router.replace("/login")}}>Sign out</button></div></header>
 {msg&&<div className="adminNotice">{msg}</div>}{loading?<div className="saSkeleton"><i/><i/><i/><i/></div>:d&&<><section className="studentNotifications"><div><p className="eyebrow">NOTIFICATIONS</p><h2>Updates that need your attention</h2></div><div className="notificationList">{d.posts.filter(p=>p.status==="APPROVED"||p.status==="REJECTED"||p.rejectionReason).slice(0,3).map(p=><a href="#submission-status" key={p.id} className={"notificationItem "+p.status.toLowerCase()}><span className="notificationDot"/><div><strong>{p.status==="APPROVED"?"Submission approved":"Submission needs attention"}</strong><small>{p.title}{p.rejectionReason?" • Faculty feedback: "+p.rejectionReason:""}</small></div><b>View</b></a>)}{!d.posts.some(p=>p.status==="APPROVED"||p.status==="REJECTED"||p.rejectionReason)&&<div className="notificationEmpty"><strong>You're all caught up</strong><small>Approval, rejection and faculty feedback updates will appear here.</small></div>}</div></section><section className="studentStats"><article><span>Total Posts</span><strong>{d.totalPosts}</strong></article><article><span>Approved</span><strong>{d.approved}</strong></article><article><span>Pending</span><strong>{d.pending}</strong></article><article><span>Rejected</span><strong>{d.rejected}</strong></article></section><div className="dashColumns"><section id="submission-status"><p className="eyebrow">MY ACTIVITY</p><h2>Submission status</h2><div className="myPosts">{d.posts.map(p=><article key={p.id}><div><strong>{p.title}</strong><small>{p.category||"Achievement"}{p.createdAt?" • "+new Date(p.createdAt).toLocaleDateString():""}</small>{p.rejectionReason&&<em>Feedback: {p.rejectionReason}</em>}</div><span className={"statusPill "+p.status.toLowerCase()}>{p.status}</span></article>)}{!d.posts.length&&<p>No posts yet. Start building your verified campus profile.</p>}</div></section><section><p className="eyebrow">STUDENT WORKSPACE</p><h2>Quick actions</h2><div className="studentQuickGrid"><a href="/submit"><strong>Submit Achievement</strong><small>Upload certificate or achievement evidence</small></a><a href="/submit"><strong>Submit Project</strong><small>Send project work for faculty verification</small></a><a href="/submit"><strong>Submit Research Paper</strong><small>Add research work and supporting evidence</small></a><a href="#submission-status"><strong>View Approval Status</strong><small>Track pending, approved and rejected records</small></a></div></section></div></>}
 {edit&&<div className="modalBack" onClick={()=>setEdit(false)}><div className="confirmModal profileModal" onClick={e=>e.stopPropagation()}><span>PROFILE SETTINGS</span><h2>Update student profile</h2><label>Display name<input value={name} onChange={e=>setName(e.target.value)} /></label><label>Study year<input value={year} onChange={e=>setYear(e.target.value)} placeholder="e.g. 3rd Year"/></label><label>Profile photo URL<input value={photo} onChange={e=>setPhoto(e.target.value)} placeholder="https://…"/></label><div><button onClick={()=>setEdit(false)}>Cancel</button><button onClick={()=>void saveProfile()}>Save profile</button></div></div></div>}
 </main>
}